# Generated by Django 3.0.6 on 2020-05-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='apellidos')),
                ('country', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_require', models.DateField(verbose_name='fecha_prestamo')),
                ('date_return', models.DateField(verbose_name='fecha_devolución')),
                ('returned', models.BooleanField(blank=True, null=True, verbose_name='devuelto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.Book')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Lector')),
            ],
        ),
    ]
