# Generated by Django 3.0.6 on 2020-05-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name_plural': 'Lectores'},
        ),
    ]
