# Generated by Django 3.0.6 on 2020-05-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20200525_1243'),
        ('prestamos', '0002_auto_20200525_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.Book'),
        ),
    ]
