# Generated by Django 3.0.6 on 2020-05-26 05:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20200525_1243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prestamo',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='date_return',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_devolución'),
        ),
    ]
